code --install-extension aaron-bond.better-comments
code --install-extension alexisvt.flutter-snippets
code --install-extension Angular.ng-template
code --install-extension asvetliakov.vscode-neovim
code --install-extension CodeStream.codestream
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension FelixAngelov.bloc
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension icrawl.discord-vscode
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension luanpotter.dart-import
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension Nash.awesome-flutter-snippets
code --install-extension njpwerner.autodocstring
code --install-extension nrwl.angular-console
code --install-extension oouo-diogo-perdigao.docthis
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension royaction.color-manager
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WakaTime.vscode-wakatimee