code --install-extension aaron-bond.better-comments
code --install-extension adashen.vscode-tomcat
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension alexisvt.flutter-snippets
code --install-extension amatiasq.sort-imports
code --install-extension Angular.ng-template
code --install-extension asvetliakov.vscode-neovim
code --install-extension CodeStream.codestream
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension FelixAngelov.bloc
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension firsttris.vscode-jest-runner
code --install-extension foxundermoon.shell-format
code --install-extension GabrielBB.vscode-lombok
code --install-extension icrawl.discord-vscode
code --install-extension James-Yu.latex-workshop
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension loiane.java-spring-extension-pack
code --install-extension luanpotter.dart-import
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension Nash.awesome-flutter-snippets
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension nrwl.angular-console
code --install-extension oouo-diogo-perdigao.docthis
code --install-extension Orta.vscode-jest
code --install-extension patbenatar.advanced-new-file
code --install-extension Pivotal.vscode-boot-dev-pack
code --install-extension Pivotal.vscode-spring-boot
code --install-extension PKief.material-icon-theme
code --install-extension raynigon.nginx-formatter
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension ritwickdey.LiveServer
code --install-extension royaction.color-manager
code --install-extension shanoor.vscode-nginx
code --install-extension shengchen.vscode-checkstyle
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension sleistner.vscode-fileutils
code --install-extension SonarSource.sonarlint-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WakaTime.vscode-wakatime
code --install-extension yassh.copy-with-line-numbers
